server:
  port: 19099
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-threads: 2000
    accept-count: 2000
    max-connections: 5000
    min-spare-threads: 4
  connection-timeout: 5000
#
# easytoolsoft
#
easytoolsoft:
    easyreport:
        common:
            item1: item1
            item2: item2
        env:
            app-name: EasyReport
            name: dev
            version: 2.1
        member:
            datasource:
                driver-class-name: com.mysql.jdbc.Driver
                password: 123456
                url: jdbc:mysql://localhost:3306/easyreport?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
                username: root
        meta:
            datasource:
                driver-class-name: com.mysql.jdbc.Driver
                password: 123456
                url: jdbc:mysql://localhost:3306/easyreport?tinyInt1isBit=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
                username: root
        shiro:
            filters: authc,membership

#
# spring
#
spring:
    messages:
        always-use-message-format: true
        basename: messages/messages
        cache-seconds: 3600
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.MysqlDialect
        hibernate:
            ddl-auto: none
#
# logging
#
logging:
  config: classpath:conf/logging/logback-spring.xml
  path: easyreport-web/target/logs
  level:
    default: INFO
    ucenter: debug
    mybatis: debug
#
# management
#
management:
    security:
        enabled: false
    add-application-context-header: false
#
# custom spring mvc
#
my:
    spring:
        mvc:
            response-body:
                base-package: com.easytoolsoft.easyreport.web.controller